syntax = "proto3";
package raft;

option go_package = "github.com/SagarSingh2003/server/raft_proto";

service Raft{
    rpc AppendEntries (AppendEntriesRequest) returns (AppendEntriesResponse) {}
//    rpc RequestVote (RequestVoteMessage) returns (RequestVoteResponse) {}
}

message AppendEntriesRequest{
    int32 term = 1;
    string leaderId = 2;
    int32 prevLogIndex = 3;
    int32 prevLogTerm = 4;
    string entries = 5;
    int32 leaderCommit = 6;
}

message AppendEntriesResponse{
    int32 term = 1;
    bool success = 2; 
}